version: '3'
services:

  mysql:
    image: mysql:8
    container_name: mymysql
    restart: always
    privileged: true
    environment:
      TZ: Asia/Shanghai
      # 设置 root 用户密码
      MYSQL_ROOT_PASSWORD: mysql_hm1234
      # 新建数据库
      MYSQL_DATABASE: hmsql
      # 创建新的用户
      MYSQL_USER: hm
      MYSQL_PASSWORD: mysql_hm1234
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/lib:/var/lib/mysql
      - /home/mysql/log:/var/log/mysql
     # - /home/mysql/my.cnf:/etc/my.cnf
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    networks:
      - hm-server

  nginx:
    image: nginx
    container_name: mynginx
    restart: always
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 挂载nginx目录
      - /home/nginx/share:/usr/share/nginx
      # 挂载nginx日志
      - /home/nginx/log:/var/log/nginx
      # 挂载nginx配置文件
      - /home/nginx/conf.d:/etc/nginx/conf.d
      - /home/nginx/ssl:/etc/nginx/ssl
    networks:
      - hm-server

  hm:
    container_name: myhm
    restart: always
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # 挂载代码，方便同步上传
      - /home/hm:/hm
    depends_on:
      - mysql
      - nginx
    entrypoint: ["./wait-for-it.sh", "mymysql:3306", "--", "air"]

    networks:
      - hm-server

networks:
  hm-server: